### PR TITLE
Add check wifi state

### PR DESCRIPTION
**Pull request by mafanwei**
#### Description

Added code to determine if you are connected to the specified wifi

### CODE REVIEW

**Comment by ThanosFisherman** [comment]
Hello @mafanwei this pull request has been open for quite some time. Let me know if you intend to fix those issues so I can proceed to a merge. Otherwise I will fix it myself and close this.

**Comment by mafanwei** [comment]
What do you expect me to fix?

**Comment by mafanwei** [comment]
link # 20

**Comment by ThanosFisherman** [comment]
@mafanwei As soon as you apply the corrections pending above, it will be ready to merge. I already explained in detail what the problem is. Are you able to see it? https://github.com/ThanosFisherman/WifiUtils/pull/70/files/756d8d99fdcaed6159ae48c00f62602adc236cf7

**Comment by ThanosFisherman** [comment]
@mafanwei Thanks for your contribution I merged your pull requests and fixed the logical errors myself. Not a big deal after all. :)

**Pull request merged**
